### ISSUE TITLE
start JFilechooser with spezified directory fails

### ISSUE THREAD

**Issue by GoogleCodeExporter** [amunra2112/gtkjfilechooser#83] opened 2015-06-04 19:59 UTC
```
What steps will reproduce the problem?
1.if ("GTK look and feel".equals(UIManager.getLookAndFeel().getName())) {
				UIManager.put("FileChooserUI", "eu.kostia.gtkjfilechooser.ui.GtkFileChooserUI");
			}
JFileChooser chooser = new JFileChooser(<any path to a directory>);


What is the expected output? 
The JFileChooser should be in the specified directory,

What do you see instead?
Is always in the home directory

Can you attach an Exception stacktrace or a screenshot?
there are no exceptions


What version of the gtkjfilechooser are you using?
1.4.9

What linux/unix distro are you using and which version of gtk (use "uname
-a" and "pkg-config --modversion gtk+-2.0" to get both information)?

Ubuntu 10.04 gtk 2.12

Please provide any additional information below.


```

Original issue reported on code.google.com by `mic.jaku...@gmail.com` on 28 Aug 2011 at 12:19

**Comment by amunra2112** [comment] 2015-06-05 15:07
Duplicate of  setCurrentDirectory is not working #85

**Closed** 2015-06-05 15:07 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
